name: Monitor Diario Tesouro

on:
  schedule:
    - cron: '0 13 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar bibliotecas
        run: pip install requests

      - name: Rodar o monitor
        run: python monitor.py
